### ISSUE TITLE
Forced to make my Model module public

### ISSUE THREAD

**Issue by antimora** [tracel-ai/burn#1158]
**Describe the bug**
I am forced to make my Model module public.

**To Reproduce**
1. declare model as private. 
2. build with ubuntu-22.04, 1.71.0, std

The error:

```
 error[E0446]: private type `ConvBlock<B>` in public interface
    --> burn-import/pytorch-tests/tests/complex_nested/mod.rs:23:10
     |
  18 | struct ConvBlock<B: Backend> {
     | ---------------------------- `ConvBlock<B>` declared as private
  ...
  23 | #[derive(Module, Debug)]
     |          ^^^^^^ can't leak private type
     |
     = note: this error originates in the derive macro `burn::record::Record` (in Nightly builds, run with -Z macro-backtrace for more info)
  
```
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 ubuntu-22.04, 1.71.0, std

**Comment by antimora** [comment]
We can close it now since we are support 1.75+ Rust only.
