### ISSUE TITLE
burn-cuda backend unusable for batched inference on CC 6.0 (Pascal)

### ISSUE THREAD

**Issue by Sean-WangXin** [tracel-ai/burn#4862]
**Describe the bug**

The burn-cuda backend crashes with `CUDA_ERROR_ILLEGAL_ADDRESS` when running batched inference on GPUs with Compute Capability 6.0 (Pascal, e.g. Tesla P100, GTX 1080 Ti). Single-batch forward passes (`batch_size=1`) work correctly, but any batched matmul (`batch_size > 1`) or sampling ops (`topk()`, `cumsum()`, `sort()`) fail at runtime.

The underlying cause is that cubecl 0.9 generates PTX instructions unavailable on CC 6.0. The PTX assembles successfully but causes illegal memory access errors when executed on Pascal hardware.

**To Reproduce**

1. Build a burn project with `burn-cuda` feature on a CC 6.0 GPU (Tesla P100, GTX 1080 Ti)
2. Run any model with batched input (e.g. `Tensor::matmul` with shape `[B, T, D]` where B > 1)
3. Observe crash:

```
thread panicked at cubecl-runtime-0.9.0/src/tune/local.rs:177:30:
Should run when selected by autotune.: Unknown {
    name: "matmul_simple_unit_min_tile_size",
    err: "Unable to launch matmul..."
}
```

4. Even with `CUBECL_AUTOTUNE_LEVEL=0`:

```
thread panicked at burn-cubecl-0.20.1/src/kernel/unary_numeric.rs:82:14:
Kernel to never fail: A compilation error happened during launch
Caused by:
  Unable to load the PTX: DriverError(CUDA_ERROR_ILLEGAL_ADDRESS,
  "an illegal memory access was encountered")
```

Sampling ops (`topk()`, `cumsum()`, `sort()`) fail identically regardless of autotune level.

**Expected behavior**

Batched inference should work on CC 6.0 GPUs, either by selecting compatible kernel variants or by falling back to a simpler implementation. Pascal GPUs (P100, GTX 1080 Ti) are still widely deployed in data centers and should be supported by burn-cuda.

At minimum, there should be a way to constrain kernel selection to CC 6.0-compatible operations, or a graceful fallback for unsupported ops.

**Screenshots**

N/A

**Desktop (please complete the following information):**

- OS: Linux
- Browser: N/A
- Version: N/A

**Smartphone (please complete the following information):**

N/A

**Additional context**

| Component | Version |
|-----------|---------|
| burn | 0.20.1 |
| burn-cuda | 0.20.1 |
| cubecl | 0.9.x |
| CUDA Driver | 12.7 |
| CUDA Toolkit | 12.6 |
| GPU | Tesla P100 (16GB, CC 6.0) |
| Rust | 1.94 |

**Working ops**: `zeros()`, `from_floats()`, `cat()`, `slice()`, `slice_assign()`, `reshape()`, element-wise arithmetic, `softmax`, `relu`, `sum`, `max`, `argmax`

**Broken ops**: batched `matmul` (B > 1), `topk()`, `cumsum()`, `sort()`, `Tensor::from_data()` on large tensors

**Impact**: Forced to sequential single-request inference, losing ~30x throughput. Only greedy decode (argmax) works; temperature-based sampling is completely broken.

**Comment by laggui** [comment]
> At minimum, there should be a way to constrain kernel selection to CC 6.0-compatible operations, or a graceful fallback for unsupported ops.

That's fair. There should be a way to execute your program, even if it means losing performance of more recent CC operations.

Right now there is no good way to configure any of that.

Linking to https://github.com/tracel-ai/cubecl/issues/1311

Also, have you tried the wgpu or vulkan backend?

**Comment by Sean-WangXin** [comment]
the code is first write on mac m1max using wgpu no problem

**Comment by antimora** [comment]
Marked blocked upstream on cubecl#1311 (selecting kernels by compute capability).
